<?php
$dalTables_matakuliah_kurikulum = array();
$dalTables_matakuliah_kurikulum["mkkurId"] = array("type"=>20,"varname"=>"mkkurId", "name" => "mkkurId");
$dalTables_matakuliah_kurikulum["mkkurProdiKode"] = array("type"=>3,"varname"=>"mkkurProdiKode", "name" => "mkkurProdiKode");
$dalTables_matakuliah_kurikulum["mkkurProdikonsentrasiId"] = array("type"=>2,"varname"=>"mkkurProdikonsentrasiId", "name" => "mkkurProdikonsentrasiId");
$dalTables_matakuliah_kurikulum["mkkurKode"] = array("type"=>200,"varname"=>"mkkurKode", "name" => "mkkurKode");
$dalTables_matakuliah_kurikulum["mkkurNamaResmi"] = array("type"=>200,"varname"=>"mkkurNamaResmi", "name" => "mkkurNamaResmi");
$dalTables_matakuliah_kurikulum["mkkurNamaAsing"] = array("type"=>200,"varname"=>"mkkurNamaAsing", "name" => "mkkurNamaAsing");
$dalTables_matakuliah_kurikulum["mkkurNamaSingkat"] = array("type"=>200,"varname"=>"mkkurNamaSingkat", "name" => "mkkurNamaSingkat");
$dalTables_matakuliah_kurikulum["mkkurNamaAsingSingkat"] = array("type"=>200,"varname"=>"mkkurNamaAsingSingkat", "name" => "mkkurNamaAsingSingkat");
$dalTables_matakuliah_kurikulum["mkkurKurId"] = array("type"=>20,"varname"=>"mkkurKurId", "name" => "mkkurKurId");
$dalTables_matakuliah_kurikulum["mkkurSemesterKurikulum"] = array("type"=>16,"varname"=>"mkkurSemesterKurikulum", "name" => "mkkurSemesterKurikulum");
$dalTables_matakuliah_kurikulum["mkkurJenisSemester"] = array("type"=>16,"varname"=>"mkkurJenisSemester", "name" => "mkkurJenisSemester");
$dalTables_matakuliah_kurikulum["mkkurTpmkrKode"] = array("type"=>200,"varname"=>"mkkurTpmkrKode", "name" => "mkkurTpmkrKode");
$dalTables_matakuliah_kurikulum["mkkurSfmkrId"] = array("type"=>200,"varname"=>"mkkurSfmkrId", "name" => "mkkurSfmkrId");
$dalTables_matakuliah_kurikulum["mkkurSfmkrKode"] = array("type"=>200,"varname"=>"mkkurSfmkrKode", "name" => "mkkurSfmkrKode");
$dalTables_matakuliah_kurikulum["mkkurJmkKode"] = array("type"=>200,"varname"=>"mkkurJmkKode", "name" => "mkkurJmkKode");
$dalTables_matakuliah_kurikulum["mkkurJkurKode"] = array("type"=>200,"varname"=>"mkkurJkurKode", "name" => "mkkurJkurKode");
$dalTables_matakuliah_kurikulum["mkkurStatusAktif"] = array("type"=>129,"varname"=>"mkkurStatusAktif", "name" => "mkkurStatusAktif");
$dalTables_matakuliah_kurikulum["mkkurBiId"] = array("type"=>20,"varname"=>"mkkurBiId", "name" => "mkkurBiId");
$dalTables_matakuliah_kurikulum["mkkurJumlahSksKurikulum"] = array("type"=>16,"varname"=>"mkkurJumlahSksKurikulum", "name" => "mkkurJumlahSksKurikulum");
$dalTables_matakuliah_kurikulum["mkkurJumlahSksTeori"] = array("type"=>16,"varname"=>"mkkurJumlahSksTeori", "name" => "mkkurJumlahSksTeori");
$dalTables_matakuliah_kurikulum["mkkurJumlahSksPraktikum"] = array("type"=>16,"varname"=>"mkkurJumlahSksPraktikum", "name" => "mkkurJumlahSksPraktikum");
$dalTables_matakuliah_kurikulum["mkkurJumlahSksPraktikumLapangan"] = array("type"=>16,"varname"=>"mkkurJumlahSksPraktikumLapangan", "name" => "mkkurJumlahSksPraktikumLapangan");
$dalTables_matakuliah_kurikulum["mkkurBobotNilaiMinimalLulus"] = array("type"=>14,"varname"=>"mkkurBobotNilaiMinimalLulus", "name" => "mkkurBobotNilaiMinimalLulus");
$dalTables_matakuliah_kurikulum["mkkurSyaratSksWajibMin"] = array("type"=>16,"varname"=>"mkkurSyaratSksWajibMin", "name" => "mkkurSyaratSksWajibMin");
$dalTables_matakuliah_kurikulum["mkkurSyaratSksPilihanMin"] = array("type"=>16,"varname"=>"mkkurSyaratSksPilihanMin", "name" => "mkkurSyaratSksPilihanMin");
$dalTables_matakuliah_kurikulum["mkkurSyaratSksTotal"] = array("type"=>16,"varname"=>"mkkurSyaratSksTotal", "name" => "mkkurSyaratSksTotal");
$dalTables_matakuliah_kurikulum["mkkurSyaratSksWajibLulusMin"] = array("type"=>16,"varname"=>"mkkurSyaratSksWajibLulusMin", "name" => "mkkurSyaratSksWajibLulusMin");
$dalTables_matakuliah_kurikulum["mkkurSyaratSksPilihanLulusMin"] = array("type"=>16,"varname"=>"mkkurSyaratSksPilihanLulusMin", "name" => "mkkurSyaratSksPilihanLulusMin");
$dalTables_matakuliah_kurikulum["mkkurSyaratSksTotalLulusMin"] = array("type"=>16,"varname"=>"mkkurSyaratSksTotalLulusMin", "name" => "mkkurSyaratSksTotalLulusMin");
$dalTables_matakuliah_kurikulum["mkkurSyaratIpk"] = array("type"=>14,"varname"=>"mkkurSyaratIpk", "name" => "mkkurSyaratIpk");
$dalTables_matakuliah_kurikulum["mkkurMaxMengulang"] = array("type"=>16,"varname"=>"mkkurMaxMengulang", "name" => "mkkurMaxMengulang");
$dalTables_matakuliah_kurikulum["mkkurSilabusPathFile"] = array("type"=>200,"varname"=>"mkkurSilabusPathFile", "name" => "mkkurSilabusPathFile");
$dalTables_matakuliah_kurikulum["mkkurSilabusDeskripsi"] = array("type"=>201,"varname"=>"mkkurSilabusDeskripsi", "name" => "mkkurSilabusDeskripsi");
$dalTables_matakuliah_kurikulum["mkkurIsAdaSatuanAcaraPerkuliahan"] = array("type"=>16,"varname"=>"mkkurIsAdaSatuanAcaraPerkuliahan", "name" => "mkkurIsAdaSatuanAcaraPerkuliahan");
$dalTables_matakuliah_kurikulum["mkkurIsAdaBahanAjar"] = array("type"=>16,"varname"=>"mkkurIsAdaBahanAjar", "name" => "mkkurIsAdaBahanAjar");
$dalTables_matakuliah_kurikulum["mkkurIsAdaDiktat"] = array("type"=>16,"varname"=>"mkkurIsAdaDiktat", "name" => "mkkurIsAdaDiktat");
$dalTables_matakuliah_kurikulum["mkkurIsFakultas"] = array("type"=>129,"varname"=>"mkkurIsFakultas", "name" => "mkkurIsFakultas");
$dalTables_matakuliah_kurikulum["mkkurIsAdaPetunjukPraktikum"] = array("type"=>16,"varname"=>"mkkurIsAdaPetunjukPraktikum", "name" => "mkkurIsAdaPetunjukPraktikum");
$dalTables_matakuliah_kurikulum["mkkurIsAdaSertifikat"] = array("type"=>16,"varname"=>"mkkurIsAdaSertifikat", "name" => "mkkurIsAdaSertifikat");
$dalTables_matakuliah_kurikulum["mkkurPegNipDosenPengampu"] = array("type"=>200,"varname"=>"mkkurPegNipDosenPengampu", "name" => "mkkurPegNipDosenPengampu");
$dalTables_matakuliah_kurikulum["mkkurBaris"] = array("type"=>200,"varname"=>"mkkurBaris", "name" => "mkkurBaris");
$dalTables_matakuliah_kurikulum["mkkurBarisEng"] = array("type"=>200,"varname"=>"mkkurBarisEng", "name" => "mkkurBarisEng");
$dalTables_matakuliah_kurikulum["mkkur1"] = array("type"=>200,"varname"=>"mkkur1", "name" => "mkkur1");
$dalTables_matakuliah_kurikulum["mkkur2"] = array("type"=>200,"varname"=>"mkkur2", "name" => "mkkur2");
$dalTables_matakuliah_kurikulum["mkkur3"] = array("type"=>200,"varname"=>"mkkur3", "name" => "mkkur3");
$dalTables_matakuliah_kurikulum["mkkur4"] = array("type"=>200,"varname"=>"mkkur4", "name" => "mkkur4");
	$dalTables_matakuliah_kurikulum["mkkurId"]["key"]=true;

$dal_info["gtakademik_dev_at_localhost__s_matakuliah_kurikulum"] = &$dalTables_matakuliah_kurikulum;
?>