<?php
$dalTablepegawai = array();
$dalTablepegawai["pegNip"] = array("type"=>200,"varname"=>"pegNip", "name" => "pegNip");
$dalTablepegawai["pegLokkerrKode"] = array("type"=>3,"varname"=>"pegLokkerrKode", "name" => "pegLokkerrKode");
$dalTablepegawai["pegFakKode"] = array("type"=>2,"varname"=>"pegFakKode", "name" => "pegFakKode");
$dalTablepegawai["pegJurKode"] = array("type"=>2,"varname"=>"pegJurKode", "name" => "pegJurKode");
$dalTablepegawai["pegProdiKode"] = array("type"=>3,"varname"=>"pegProdiKode", "name" => "pegProdiKode");
$dalTablepegawai["pegRuId"] = array("type"=>20,"varname"=>"pegRuId", "name" => "pegRuId");
$dalTablepegawai["pegStpegrId"] = array("type"=>2,"varname"=>"pegStpegrId", "name" => "pegStpegrId");
$dalTablepegawai["pegNama"] = array("type"=>200,"varname"=>"pegNama", "name" => "pegNama");
$dalTablepegawai["pegNomorKtp"] = array("type"=>200,"varname"=>"pegNomorKtp", "name" => "pegNomorKtp");
$dalTablepegawai["pegGelarDepan"] = array("type"=>200,"varname"=>"pegGelarDepan", "name" => "pegGelarDepan");
$dalTablepegawai["pegGelarBelakang"] = array("type"=>200,"varname"=>"pegGelarBelakang", "name" => "pegGelarBelakang");
$dalTablepegawai["pegKotaKodeLahir"] = array("type"=>200,"varname"=>"pegKotaKodeLahir", "name" => "pegKotaKodeLahir");
$dalTablepegawai["pegNgrKodeLahir"] = array("type"=>200,"varname"=>"pegNgrKodeLahir", "name" => "pegNgrKodeLahir");
$dalTablepegawai["pegTanggalLahir"] = array("type"=>7,"varname"=>"pegTanggalLahir", "name" => "pegTanggalLahir");
$dalTablepegawai["pegKartuPegawai"] = array("type"=>200,"varname"=>"pegKartuPegawai", "name" => "pegKartuPegawai");
$dalTablepegawai["pegStambuk"] = array("type"=>200,"varname"=>"pegStambuk", "name" => "pegStambuk");
$dalTablepegawai["pegJenisKelaminKode"] = array("type"=>129,"varname"=>"pegJenisKelaminKode", "name" => "pegJenisKelaminKode");
$dalTablepegawai["pegGolonganDarah"] = array("type"=>200,"varname"=>"pegGolonganDarah", "name" => "pegGolonganDarah");
$dalTablepegawai["pegAgmrId"] = array("type"=>2,"varname"=>"pegAgmrId", "name" => "pegAgmrId");
$dalTablepegawai["pegStnkrId"] = array("type"=>2,"varname"=>"pegStnkrId", "name" => "pegStnkrId");
$dalTablepegawai["pegAlamatRumah"] = array("type"=>200,"varname"=>"pegAlamatRumah", "name" => "pegAlamatRumah");
$dalTablepegawai["pegLokalrKode"] = array("type"=>3,"varname"=>"pegLokalrKode", "name" => "pegLokalrKode");
$dalTablepegawai["pegKotaKode"] = array("type"=>200,"varname"=>"pegKotaKode", "name" => "pegKotaKode");
$dalTablepegawai["pegNgrKode"] = array("type"=>200,"varname"=>"pegNgrKode", "name" => "pegNgrKode");
$dalTablepegawai["pegKodePos"] = array("type"=>200,"varname"=>"pegKodePos", "name" => "pegKodePos");
$dalTablepegawai["pegNoTelpKantor"] = array("type"=>200,"varname"=>"pegNoTelpKantor", "name" => "pegNoTelpKantor");
$dalTablepegawai["pegNoTelpRumah"] = array("type"=>200,"varname"=>"pegNoTelpRumah", "name" => "pegNoTelpRumah");
$dalTablepegawai["pegNoHP"] = array("type"=>200,"varname"=>"pegNoHP", "name" => "pegNoHP");
$dalTablepegawai["pegNoFax"] = array("type"=>200,"varname"=>"pegNoFax", "name" => "pegNoFax");
$dalTablepegawai["pegEmail"] = array("type"=>200,"varname"=>"pegEmail", "name" => "pegEmail");
$dalTablepegawai["pegJnpegrId"] = array("type"=>2,"varname"=>"pegJnpegrId", "name" => "pegJnpegrId");
$dalTablepegawai["pegSkTempatLahir"] = array("type"=>200,"varname"=>"pegSkTempatLahir", "name" => "pegSkTempatLahir");
$dalTablepegawai["pegNoSKCpns"] = array("type"=>200,"varname"=>"pegNoSKCpns", "name" => "pegNoSKCpns");
$dalTablepegawai["pegTanggalSKCpns"] = array("type"=>7,"varname"=>"pegTanggalSKCpns", "name" => "pegTanggalSKCpns");
$dalTablepegawai["pegTmtCpns"] = array("type"=>7,"varname"=>"pegTmtCpns", "name" => "pegTmtCpns");
$dalTablepegawai["pegGolrKodeCpns"] = array("type"=>200,"varname"=>"pegGolrKodeCpns", "name" => "pegGolrKodeCpns");
$dalTablepegawai["pegMasKerThCpns"] = array("type"=>16,"varname"=>"pegMasKerThCpns", "name" => "pegMasKerThCpns");
$dalTablepegawai["pegMasKerBlCpns"] = array("type"=>16,"varname"=>"pegMasKerBlCpns", "name" => "pegMasKerBlCpns");
$dalTablepegawai["pegTanggalPraJabatan"] = array("type"=>7,"varname"=>"pegTanggalPraJabatan", "name" => "pegTanggalPraJabatan");
$dalTablepegawai["pegNoSKPns"] = array("type"=>200,"varname"=>"pegNoSKPns", "name" => "pegNoSKPns");
$dalTablepegawai["pegTanggalSKPns"] = array("type"=>7,"varname"=>"pegTanggalSKPns", "name" => "pegTanggalSKPns");
$dalTablepegawai["pegTmtPns"] = array("type"=>7,"varname"=>"pegTmtPns", "name" => "pegTmtPns");
$dalTablepegawai["pegGolrKodePns"] = array("type"=>200,"varname"=>"pegGolrKodePns", "name" => "pegGolrKodePns");
$dalTablepegawai["pegTanggalSumpahPns"] = array("type"=>7,"varname"=>"pegTanggalSumpahPns", "name" => "pegTanggalSumpahPns");
$dalTablepegawai["pegTanggalDiGT"] = array("type"=>7,"varname"=>"pegTanggalDiGT", "name" => "pegTanggalDiGT");
$dalTablepegawai["pegNomorKartuTaspen"] = array("type"=>200,"varname"=>"pegNomorKartuTaspen", "name" => "pegNomorKartuTaspen");
$dalTablepegawai["pegInstansiAsal"] = array("type"=>200,"varname"=>"pegInstansiAsal", "name" => "pegInstansiAsal");
$dalTablepegawai["pegIsAktif"] = array("type"=>16,"varname"=>"pegIsAktif", "name" => "pegIsAktif");
$dalTablepegawai["pegCatatan"] = array("type"=>200,"varname"=>"pegCatatan", "name" => "pegCatatan");
$dalTablepegawai["pegTanggalPengubahan"] = array("type"=>7,"varname"=>"pegTanggalPengubahan", "name" => "pegTanggalPengubahan");
$dalTablepegawai["pegWnrId"] = array("type"=>2,"varname"=>"pegWnrId", "name" => "pegWnrId");
$dalTablepegawai["pegAlamatSurat"] = array("type"=>200,"varname"=>"pegAlamatSurat", "name" => "pegAlamatSurat");
$dalTablepegawai["pegKelurahan"] = array("type"=>200,"varname"=>"pegKelurahan", "name" => "pegKelurahan");
$dalTablepegawai["pegKecamatan"] = array("type"=>200,"varname"=>"pegKecamatan", "name" => "pegKecamatan");
$dalTablepegawai["pegNamaIbu"] = array("type"=>200,"varname"=>"pegNamaIbu", "name" => "pegNamaIbu");
$dalTablepegawai["pegNpwp"] = array("type"=>200,"varname"=>"pegNpwp", "name" => "pegNpwp");
$dalTablepegawai["pegRekening"] = array("type"=>200,"varname"=>"pegRekening", "name" => "pegRekening");
$dalTablepegawai["pegKotaKodeSurat"] = array("type"=>200,"varname"=>"pegKotaKodeSurat", "name" => "pegKotaKodeSurat");
$dalTablepegawai["pegKodePosSurat"] = array("type"=>200,"varname"=>"pegKodePosSurat", "name" => "pegKodePosSurat");
	$dalTablepegawai["pegNip"]["key"]=true;

$dal_info["gtakademik_dev_at_localhost__pegawai"] = &$dalTablepegawai;
?>